repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.0
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports, --config-file=setup.cfg]
        exclude: "test/|^setup\\.py$"

  - repo: https://github.com/google/yapf
    rev: v0.32.0
    hooks:
      - id: yapf
        args: [ -r, -i ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [ --config=setup.cfg, --count, --show-source, --statistics ]
        additional_dependencies: [ "flake8_bugbear" ]